# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipoidentidicacion', models.IntegerField(choices=[(1, 'cedula'), (2, 'Tarjeta identidad'), (3, 'Pasaporte'), (4, 'Contraseña')], default=1)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('tel', models.IntegerField()),
                ('cel', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('Cod_ciudad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('Cod_departamento', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='Cod_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Departamento'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Ciudad'),
        ),
    ]
