# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0003_auto_20161130_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
