# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0004_auto_20161130_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='arrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unidad_arrendatario', to='edificios.Persona'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unidad_propietario', to='edificios.Persona'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unidad_residente', to='edificios.Persona'),
        ),
    ]
