# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0005_auto_20161130_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='arrendatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unidad_arrendatario', to='edificios.Persona'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='forma_recibo',
            field=models.IntegerField(choices=[(1, 'Fisico'), (2, 'Email')], default=1),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='residente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Unidad_residente', to='edificios.Persona'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='saldo_favor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='valor_mora',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='valor_pago',
            field=models.IntegerField(blank=True),
        ),
    ]
