# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0006_auto_20161130_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidad',
            old_name='Responsable',
            new_name='responsable',
        ),
        migrations.AlterField(
            model_name='unidad',
            name='valor_pago',
            field=models.IntegerField(),
        ),
    ]
