# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0007_auto_20161130_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='Imagen',
            field=models.ImageField(blank=True, default='Img/Propiedad/default_building_zappy.jpg', upload_to='Img/Propiedad/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Residencial'), (2, 'Comercial'), (3, 'Mixto')], default=1, verbose_name='Tipo Propiedad'),
        ),
    ]
