# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0008_auto_20161130_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
