# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0009_propiedad_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
