# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0010_auto_20161202_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='idlegal',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Identidad'),
        ),
    ]
