# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0011_auto_20161203_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
