# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0013_auto_20161204_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='dia_cobro',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='porcentaje_mora',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='saldo_favor',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='valor_mora',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
