# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('edificios', '0014_auto_20161204_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Banco', models.CharField(max_length=254, verbose_name='Banco')),
                ('tipo_cuenta', models.IntegerField(choices=[(1, 'Corriente'), (2, 'Ahorro')], default=2, verbose_name='Tipo de Cuenta')),
                ('num_cuenta', models.CharField(max_length=245)),
                ('Propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.Propiedad')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Administrador')),
            ],
            options={
                'verbose_name_plural': 'Bancos',
                'verbose_name': 'Banco',
            },
        ),
    ]
