# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0016_auto_20161205_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='num_cuenta',
            field=models.CharField(max_length=245, verbose_name='# Cuenta'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='coeficiente',
            field=models.FloatField(default=1.0),
        ),
    ]
